import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Ingredient, FullRecipe, UserPreferences } from '../shared/interfaces';

@Injectable({
  providedIn: 'root',
})
export class Generator {
  private http = inject(HttpClient);
  private n8nWebhookUrl = 'http://localhost:5678/webhook/generate-recipe';
  private userIngredients: Ingredient[] = [];
  private generatedRecipes: FullRecipe[] = [];
  private userPrefs: UserPreferences | null = null; 

  /** Sets the user's selected cooking and dietary preferences in the service state. */
  setUserPrefs(prefs: UserPreferences): void {
    this.userPrefs = prefs;
  }

  /** Retrieves the user preferences stored during the recipe generation process. */
  getUserPrefs(): UserPreferences | null {
    return this.userPrefs;
  }

  /** Updates the internal store with the list of ingredients provided by the user. */
  setIngredients(ingredients: Ingredient[]): void {
    this.userIngredients = ingredients;
  }

  /** Returns the current list of user-provided ingredients from the service. */
  getIngredients(): Ingredient[] {
    return this.userIngredients;
  }

  /** Sends ingredients and preferences to the n8n webhook via an HTTP POST request to generate recipes. */
  generateRecipesFromN8n(preferences: UserPreferences): Observable<{ success: boolean; recipes: FullRecipe[] }> {

    const payload = {
      action: "generate_recipes",
      data: {
        ingredients: this.userIngredients.map(ing => ({
          name: ing.name,
          amount: ing.amount,
          unit: ing.unit
        })),
        preferences: {
          portions: preferences.portions,
          personsCooking: preferences.persons,
          timeLimit: preferences.time,
          cuisineStyle: preferences.cuisine,
          dietType: preferences.diet
        }
      }
    };
    
    return this.http.post<{ success: boolean; recipes: FullRecipe[] }>(this.n8nWebhookUrl, payload);
  }

  /** Stores the array of recipes generated by the AI service for later retrieval. */
  setGeneratedRecipes(recipes: FullRecipe[]): void {
    this.generatedRecipes = recipes;
  }

  /** Retrieves the collection of recipes that were successfully generated during the current session. */
  getGeneratedRecipes(): FullRecipe[] {
    return this.generatedRecipes;
  }
}